apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register$', views.register, name = 'register'),
    url(r'^login$', views.login, name = 'login'),
    url(r'^$', views.index, name = 'index'),
    url(r'^logout$', views.logout, name = 'logout'),

]

apps/quotes/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^add$', views.quote, name = 'add'),
    url(r'^about$', views.about, name = 'about'),
    url(r'^dash$', views.dash, name = 'dash'),
    url(r'^(?P<id>\d+)/favorite$', views.favorite, name = 'favorite'),
    url(r'^(?P<id>\d+)/delete$', views.delete, name = 'delete'),
    url(r'^(?P<id>\d+)/users$', views.users, name = 'users'),
]

pythonexam2/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace = 'login')),
    url(r'^quotes', include('apps.quotes.urls', namespace = 'quotes')),

]

apps/login/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
import bcrypt
import re
import datetime

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
name_regex = re.compile(r'^[A-Za-z]{2}')
password_regex = re.compile(r'^.{8}')
# Create your models here.
class LoginManager(models.Manager):
	def register(self, user, alias, email, passw, confirm, date):
		errors = []
		if User.objects.filter(alias = alias).exists() == True:
			errors.append('Alias already exists!')
		if not name_regex.match(user):
			errors.append('first name must be no fewer than 2 characters and letters only')
		if User.objects.filter(email = email).exists() == True:
			errors.append('email already in use')
		if not EMAIL_REGEX.match(email):
			errors.append('Please enter a valid email')
		if not password_regex.match(passw):
			errors.append('password must be no fewer than 8 characters')
		if passw != confirm:
			errors.append('passwords must match')
		if not date:
			errors.append('please enter a date')
		if len(errors) != 0:
			return (False, errors)
		else:
			passw = passw.encode()
			hashed = bcrypt.hashpw(passw, bcrypt.gensalt())
			e = User.objects.create(username = user, alias = alias, email = email, password = hashed, dob = date)
			e.save()
			return (True, e)
	def login(self, email, password):
		errors = []
		try:
			result = User.objects.get(email = email)
		except:
			errors.append('Email does not exist')
			return (False, errors)
		if not bcrypt.hashpw(password.encode(), result.password.encode()) == result.password.encode():
			errors.append('password is incorrect')
			return (False, errors)
		return (True, result)

class User(models.Model):
	username = models.CharField(max_length=50)
	alias = models.CharField(max_length=50)
	email = models.CharField(max_length=50)
	password = models.CharField(max_length=200)
	dob = models.DateField(blank = True, null = True)
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)
	objects = LoginManager()

apps/quotes/models.py
from __future__ import unicode_literals
from ..login.models import User
from django.db import models

# Create your models here.
class Quotes(models.Model):
	quoter = models.CharField(max_length = 100)
	quote = models.TextField()
	user = models.ForeignKey(User)

class Favorites(models.Model):
	user = models.ForeignKey(User)
	quotes = models.ForeignKey(Quotes)

apps/login/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages
from django.core.urlresolvers import reverse

def index(request):
	return render(request, 'login/index.html')

def register(request):
	result = User.objects.register(request.POST['user'], request.POST['alias'], request.POST['email'], request.POST['passw'], request.POST['confirm'], request.POST['date'])
	if result[0]:
		request.session['id'] = result[1].id
		print request.session['id']
		return redirect(reverse('quotes:index'))
	else:
		for error in result[1]:
			messages.error(request, error)
	return redirect(reverse('login:index'))

def login(request):
	result = User.objects.login(request.POST['email'], request.POST['password'])
	if result[0]:
		request.session['id'] = result[1].id
		return redirect(reverse('quotes:index'))
	else:
		for error in result[1]:
			messages.error(request, error)
	return redirect(reverse('login:index'))

def logout(request):
	request.session.flush()
	return redirect(reverse('login:index'))

apps/quotes/views.py
from django.shortcuts import render, redirect
from ..login.models import User
from django.contrib import messages
from django.core.urlresolvers import reverse
from .models import Quotes, Favorites
# Create your views here.
def index(request):
	if 'id' not in request.session:
		return redirect(reverse('login:index'))
	users = User.objects.all().order_by('alias')
	user = User.objects.get(id = request.session['id'])
	userid = request.session['id']
	favorites = Favorites.objects.filter(user = user)
	quotes = Quotes.objects.exclude(favorites__user = user)
	context = {'user':user, 'quotes':quotes, 'favorites':favorites, "userid":userid, 'users':users}
	return render(request, 'quotes/index.html', context)

def about(request):
	user = User.objects.get(id = request.session['id'])	
	context = {'user':user}
	return render(request, 'quotes/about.html', context)	

def quote(request):
	x = False
	if len(request.POST['quoter'])<3:
		messages.error(request, "Quoted by must be more than 3 characters")
		x = True
	if len(request.POST['quote'])<10:
		messages.error(request, "Quote must be greater than 10 characters")
		x = True
	if x:
		return redirect(reverse('quotes:index'))
	user = User.objects.get(id = request.session['id'])
	Quotes.objects.create(quoter = request.POST['quoter'], quote = request.POST['quote'], user = user)
	return redirect(reverse('quotes:index'))

def favorite(request, id):
	user = User.objects.get(id = request.session['id'])
	quote = Quotes.objects.get(id = id)
	Favorites.objects.create(quotes = quote, user = user)
	return redirect(reverse('quotes:index'))

def delete(request, id):
	user = User.objects.get(id = request.session['id'])
	quote = Quotes.objects.get(id = id)
	Favorites.objects.filter(quotes = id).delete()
	return redirect(reverse('quotes:index'))	

def users(request, id):
	if 'id' not in request.session:
		return redirect(reverse('login:index'))
	user = User.objects.get(id = id)
	users = User.objects.all().order_by('alias')
	print user.alias
	quotes = Quotes.objects.filter(user = user)
	count = 0 
	for quote in quotes:
		count +=1
	context = {'user':user, 'users':users, 'count':count, 'quotes':quotes}
	return render(request, 'quotes/profile.html', context)

def dash(request):
	return redirect(reverse('quotes:index'))

apps/login/templates/login/index.html
<!DOCTYPE html>
<html lang="en">
<head>

    <title>Quotable| Login & Registration</title>
    {% load static %}
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'login/stylesheet.css' %}" /> -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
    <link rel="stylesheet" href="{% static 'login/assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'login/assets/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'login/assets/css/form-elements.css' %}">
    <link rel="stylesheet" href="{% static 'login/assets/css/style.css' %}">
    <meta charset="utf-8">
    
</head>
    <body>
        <div class="top-content">  
            <div class="inner-bg">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-8 col-sm-offset-2 text">
                            <div class="description">
                            </div>
                        </div>
                    </div>
                    <h1 style="margin-bottom: 70px; font-size: 70px;">Welcome to Quotable Quotes</h1>
                    <div class="row">
                        {% for message in messages %}
                            <p id ="errorMessage">{{message}}</p>
                        {% endfor %}
                        <div class="col-sm-6 col-sm-offset-3 form-box">
                            <div class="form-top">
                                <div class="form-top-left">
                                    <h3>Login</h3>
                                </div>
                                <div class="form-top-right">
                                </div>
                            </div>
                            <div class="form-bottom">
                                <form action="login" method="post" class="login-form">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label class="sr-only" for="form-password">Email</label>
                                        <input type="text" name="email" placeholder="Email..." class="form-username form-control">
                                    </div>
                                    <div class="form-group">
                                        <label class="sr-only" for="form-password">Password</label>
                                        <input type="password" name="password" placeholder="Password..." class="form-username form-control">
                                    </div>
                                    <button type="submit" class="btn">Sign in!</button>
                                </form>
                            </div>
                        </div>
                        <div class="col-sm-6 col-sm-offset-3 form-box">
                            <div class="form-top">
                                <div class="form-top-left">
                                    <h3>Register</h3>
                                </div>
                                <div class="form-top-right">
                                </div>
                            </div>
                            <div class="form-bottom">
                                <form  action="register" method="post" class="login-form">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label class="sr-only" for="form-password">Name</label>
                                        <input type="text" name="user" placeholder="Name..." class="form-username form-control">
                                    </div>
                                    <div class="form-group">
                                        <label class="sr-only" for="form-password">Alias</label>
                                        <input type="text" name="alias" placeholder="Alias..." class="form-username form-control">
                                    </div>
                                    <div class="form-group">
                                        <label class="sr-only" for="form-password">Email</label>
                                        <input type="text" name="email" placeholder="Email..." class="form-username form-control">
                                    </div>
                                    <div class="form-group">
                                        <label class="sr-only" for="form-password">Password</label>
                                        <input type="password" name="passw" placeholder="Password..." class="form-username form-control">
                                    </div>
                                    <div class="form-group">
                                        <label class="sr-only" for="form-password">Confirm Password</label>
                                        <input type="password" name="confirm" placeholder="Confirm Password..." class="form-username form-control">
                                    </div>
                                    <div class="form-group">
                                        <label class="sr-only" for="form-password">Date of Birth</label>
                                        <input type="date" name="date" placeholder="Date Of Birth..." class="form-username form-control">
                                    </div>
                                    <button type="submit" class="btn">Register!</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
        <!-- Javascript -->
        <script src="assets/js/jquery-1.11.1.min.js"></script>
        <script src="assets/bootstrap/js/bootstrap.min.js"></script>
        <script src="assets/js/jquery.backstretch.min.js"></script>
        <script src="assets/js/scripts.js"></script> 
        <!--[if lt IE 10]>
            <script src="assets/js/placeholder.js"></script>
        <![endif]-->
    </body>
</html>

apps/quotes/templates/quotes/about.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>About</title>

    <!-- Bootstrap core CSS -->
    {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'quotes/assets/bootstrap.min.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'quotes/assets/offcanvas.css' %}" />
	<script src="{% static 'quotes/assets/offcanvas.js' %}"></script>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Quotable Quotes</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'quotes:dash' %}">Home</a></li>
            <li class="active"><a href="{% url 'quotes:about' %}">About</a></li>
            <li><a href="{% url 'quotes:users' user.id %}">Profile</a></li>
            <li><a href="{% url 'login:logout' %}">Logout</a></li>
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->

    <div class="container">

      <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          <div class="jumbotron">
            <h1>Hello, {{user.alias}}</h1>
            <p>Find, Share, and Favorite Quotes!</p>
          </div>
          <hr>
          <h1>About</h1>
          <hr>
          <p>This site is made for posting and sharing quotes. Find all kinds of quotes for however you are feeling. Can't find a quote? Add it to the list of quotes! Also make sure to add your favorite quotes so you can look back at them easily for future reference!</p>
          <p>Questions or concerns? </p>
          <p>Feel free to email me at georgehsin@ucla.edu</p>
      <footer>
        <p></p>
      </footer>

    </div><!--/.container-->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="offcanvas.js"></script>
  </body>
</html>

apps/quotes/templates/quotes/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Quotes</title>

    <!-- Bootstrap core CSS -->
    {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'quotes/assets/bootstrap.min.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'quotes/assets/offcanvas.css' %}" />
	<script src="{% static 'quotes/assets/offcanvas.js' %}"></script>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Quotable Quotes</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="{% url 'quotes:about' %}">About</a></li>
            <li><a href="{% url 'quotes:users' user.id %}">Profile</a></li>
            <li><a href="{% url 'login:logout' %}">Logout</a></li>
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->

    <div class="container">

      <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          <div class="jumbotron">
            <h1>Hello, {{user.alias}}</h1>
            <p>Find, Share, and Favorite Quotes!</p>
          </div>
          <hr>
          <h1>Quotes</h1>
          <hr>
          <div class="row">
            {% for quote in quotes %}
              <div class="col-xs-6 col-lg-4" style="min-height:200px; display:inline-block; vertical-align:top;">
                <h2>{{quote.quoter}}</h2>
                <p>"{{quote.quote}}"</p>
                <p>Posted by: <a href="{% url 'quotes:users' quote.user.id %}">{{quote.user.alias}}</a></p>
                <p><a class="btn btn-default" href="{% url 'quotes:favorite' quote.id %}">Add to My List</a></p>
              </div>
            {% endfor %}
          </div><!--/row-->
          <hr>
          <h1>Favorites</h1>
          <hr>
          <div class="row">
            {% for favorite in favorites %}
            <div class="col-xs-6 col-lg-4" style="min-height:200px; display:inline-block; vertical-align:top;">
              <h2>{{favorite.quotes.quoter}}</h2>
              <p>"{{favorite.quotes.quote}}"</p>
                <p>Posted by: <a href="{% url 'quotes:users' favorite.user.id %}">{{favorite.quotes.user.alias}}</a></p>
                <p><a class="btn btn-default" href="{% url 'quotes:delete' favorite.quotes.id %}">Remove from my list</a><p>
            </div>
            {% endfor %}
          </div><!--/row-->
        </div><!--/.col-xs-12.col-sm-9-->

        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
          <div class="list-group">
            <!-- <a href="#" class="list-group-item active">Link</a> -->
            <h3>Users:</h3>
            {% for user in users %}
            <a href="{% url 'quotes:users' user.id %}" class="list-group-item">{{user.alias}}</a>
            {% endfor %}
          </div>
          <div>
          	<h3>Contribute a Quote:</h3>
			<div id="addquote">
				<form action="{% url 'quotes:add' %}" method="post">
				{% csrf_token %}
				<p>Quoted By: <input type="text" name="quoter"></p>
				<p>Quote:<textarea cols="18" rows="5" name="quote" style="margin-left:30px;"> </textarea></p>
			 	{% for message in messages %}
	        		<p style="background-color:red;">{{message}}</p>
	   		 	{% endfor %}
				<input type="submit" name="Submit" style="margin-left:180px;">
				</form>
			</div>
          </div>

        </div><!--/.sidebar-offcanvas-->
      </div><!--/row-->

      <hr>

      <footer>
        <p></p>
      </footer>

    </div><!--/.container-->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="offcanvas.js"></script>
  </body>
</html>


<!-- <!DOCTYPE html>
<html>
<head>
	<title>Quotes</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'quotes/stylesheet.css' %}" />

</head>
<body>
	<a href="{% url 'login:logout' %}">Logout</a>
	<h2>Hello, {{user.alias}}!</h2>
	<h3>Quotable Quotes</h3>
	<hr>
	<div class="quotes">
	{% for quote in quotes %}
		<span id="quoter">{{quote.quoter}}:</span>{{quote.quote}}
		<p>Posted by:<a href="{% url 'quotes:users' quote.user.id %}">{{quote.user.alias}}</a></p>
		<a href="{% url 'quotes:favorite' quote.id %}"><button>Add to My List</button></a>
		<hr>
	{% endfor %}
	</div>
	

	<h3>Favorite Quotes</h3>
	<hr>
	<div class="quotes">
	{% for favorite in favorites %}
		{{favorite.quotes.quoter}}:{{favorite.quotes.quote}}
		<p>Posted by:<a href="{% url 'quotes:users' favorite.user.id %}">{{favorite.quotes.user.alias}}</p>
		<a href="{% url 'quotes:delete' favorite.quotes.id %}"><button>Remove from my list</button></a>
		<hr>
	{% endfor %}
	</div>
	
	<h4>Contribute a Quote:</h4>
	<div id="addquote">
		<form action="{% url 'quotes:add' %}" method="post">
			{% csrf_token %}
			Quoted By: <input type="text" name="quoter">
			<p>Quote: <textarea cols="18" rows="5" name="quote"> </textarea></p>
			 {% for message in messages %}
	        <p style="background-color:red;">{{message}}</p>
	   		 {% endfor %}
			<input type="submit" name="Submit">
	</form>
	</div>
</body>
</html>
 -->

apps/quotes/templates/quotes/profile.html
<!DOCTYPE html>
<html>
<head>
	<title>Quotes</title>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'quotes/stylesheet.css' %}" />
</head>
<body>
	<a href="{% url 'login:logout' %}">Logout</a>|<a href="{% url 'quotes:dash' %}">Dashboard</a>
	<h3>Posts by {{user.alias}} | Count: {{count}} </h3>
	<hr>

<!-- 	<div class="quotes">
	{% for favorite in favorites %}
		<p><span id="quoter">{{favorite.quotes.quoter}}</span>:{{favorite.quotes.quote}}</p>
	{% endfor %}
	</div> -->

	<div class="quotes">
	{% for quote in quotes %}
		<p><span id="quoter">{{quote.quoter}}</span>:{{quote.quote}}</p>
	{% endfor %}
	</div>


</body>
</html>